/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface demopConstants {
  public final static int NICSLU_GENERAL_FAIL = demopJNI.NICSLU_GENERAL_FAIL_get();
  public final static int NICSLU_ARGUMENT_ERROR = demopJNI.NICSLU_ARGUMENT_ERROR_get();
  public final static int NICSLU_MEMORY_OVERFLOW = demopJNI.NICSLU_MEMORY_OVERFLOW_get();
  public final static int NICSLU_FILE_CANNOT_OPEN = demopJNI.NICSLU_FILE_CANNOT_OPEN_get();
  public final static int NICSLU_MATRIX_STRUCTURAL_SINGULAR = demopJNI.NICSLU_MATRIX_STRUCTURAL_SINGULAR_get();
  public final static int NICSLU_MATRIX_NUMERIC_SINGULAR = demopJNI.NICSLU_MATRIX_NUMERIC_SINGULAR_get();
  public final static int NICSLU_MATRIX_INVALID = demopJNI.NICSLU_MATRIX_INVALID_get();
  public final static int NICSLU_MATRIX_ENTRY_DUPLICATED = demopJNI.NICSLU_MATRIX_ENTRY_DUPLICATED_get();
  public final static int NICSLU_THREADS_NOT_INITIALIZED = demopJNI.NICSLU_THREADS_NOT_INITIALIZED_get();
  public final static int NICSLU_MATRIX_NOT_INITIALIZED = demopJNI.NICSLU_MATRIX_NOT_INITIALIZED_get();
  public final static int NICSLU_SCHEDULER_NOT_INITIALIZED = demopJNI.NICSLU_SCHEDULER_NOT_INITIALIZED_get();
  public final static int NICSLU_SINGLE_THREAD = demopJNI.NICSLU_SINGLE_THREAD_get();
  public final static int NICSLU_THREADS_INIT_FAIL = demopJNI.NICSLU_THREADS_INIT_FAIL_get();
  public final static int NICSLU_MATRIX_NOT_ANALYZED = demopJNI.NICSLU_MATRIX_NOT_ANALYZED_get();
  public final static int NICSLU_MATRIX_NOT_FACTORIZED = demopJNI.NICSLU_MATRIX_NOT_FACTORIZED_get();
  public final static int NICSLU_NUMERIC_OVERFLOW = demopJNI.NICSLU_NUMERIC_OVERFLOW_get();
  public final static int NICSLU_USE_SEQUENTIAL_FACTORIZATION = demopJNI.NICSLU_USE_SEQUENTIAL_FACTORIZATION_get();
  public final static int NICSLU_BIND_THREADS_FAIL = demopJNI.NICSLU_BIND_THREADS_FAIL_get();
}
